### ISSUE TITLE
ラベルの色がダークモードで壊れてる？

### ISSUE THREAD

**Issue by habara-k** [git-deck/git-deck#152]
<img width="674" alt="スクリーンショット 2021-08-16 13 37 36" src="https://user-images.githubusercontent.com/34413567/129512093-39f00b65-17e3-4a93-bc17-dc82e12772ba.png">
<img width="674" alt="スクリーンショット 2021-08-16 13 38 35" src="https://user-images.githubusercontent.com/34413567/129512122-65352017-1f96-4c72-8653-929e6c47a5c9.png">

**Comment by habara-k** [comment]
https://github.com/git-deck/git-deck/pull/137#issuecomment-898503926

**Comment by knknk98** [comment]
わい環境では緑っぽかった
<img width="487" alt="スクリーンショット 2021-08-17 23 48 21" src="https://user-images.githubusercontent.com/65712721/129748265-afd363d0-47ab-411c-bbdc-ed982ce4c122.png">

**Comment by knknk98** [comment]
GitHubダークモードラベルのネオンっぽい色好きなんだが、規則性がよくわからん、、、

**Comment by knknk98** [comment]
<img width="496" alt="スクリーンショット 2021-08-17 23 51 43" src="https://user-images.githubusercontent.com/65712721/129748859-d5de1432-a339-4d99-8ca1-affcf38e73ab.png">
一部だけ変な色になってるのか。ついでにバグの色もおバグの色もおかしいな
なんでや、、

**Comment by knknk98** [comment]
<img width="500" alt="スクリーンショット 2021-08-17 23 52 50" src="https://user-images.githubusercontent.com/65712721/129749057-9c2dc60a-4ef5-4d2f-bcab-e025f0bf44c0.png">
該当部分、Lightモードでもちょっとおかしい

**Comment by knknk98** [comment]
<img width="434" alt="スクリーンショット 2021-08-18 0 03 42" src="https://user-images.githubusercontent.com/65712721/129751026-cd0a5f4d-d235-4a19-b0c3-373d1ceffc69.png">

（RGB）#16進数

渡されたカラーコード（#FFFFFFみたいな形のやつ）をmountedでRGBに分解してるんだけど、それがうまくいってないのが原因で起きてるバグっぽい？

**Comment by zwwaa-ku** [comment]
#177 で対応できてるか確認してほしい
出来たらマージしてください。
