### ISSUE TITLE
横スクロールできない

### ISSUE THREAD

**Issue by knknk98** [git-deck/git-deck#186]

**Comment by knknk98** [comment]
ドラッグとリサイズで別ライブラリを使っているんだが、リサイズだけ消したら横スクロールするようになったのでリサイズの方の問題かも

**Comment by knknk98** [comment]
VueResizable自体マイナーなのであまり更新されてないのでライブラリ変えてもいいかも

**Comment by yuta-ike** [comment]
大体ライブラリあるなら変えた方が良いかもですね。。時間との相談ですが。
